greetingClient:
  baseUri: ${GREETING_BASE_URI:-http://localhost:8080/}
  username: ${GREETING_USERNAME:-Alfonso}
  password: ${GREETING_PASSWORD:-password}
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
logging:
  level: INFO
  loggers:
    tech.dimas: DEBUG
