networkClient:
  baseUri: https://fwd.app/api/
  username: 'username'
  password: 'password'

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
logging:
  level: INFO
  loggers:
    tech.dimas: DEBUG
